pipeline {
  agent any 
 tools {
   maven 'maven'
 }
  stages {
    stage ('test'){
      steps {
        script {
          test()
        }
      }
    } 
    stage ('Sonar code analysis'){
      steps {
        script {
          code_analysis()
        }
      }
    }
    stage ('build'){
      steps {
        script {
          build()
        }
      }
    }  
  }
}
