pipeline {
  agent any 
 tools {
   maven 'maven'
 }
  stages {
    stage ("linting") {
      steps {
        script {
          lint()
        }
      }
    }
    stage ('test'){
      steps {
        script {
          test()
        }
      }
    } 
    stage ('Sonar code analysis'){
      steps {
        script {
          code_analysis()
        }
      }
    }
    stage ('build'){
      steps {
        script {
          build()
        }
      }
    } 
    stage ('Publish Artifacts') {
      steps {
        script {
          publish_package()
        }
      }
    }
  }
}
